### ISSUE TITLE
I'm having some problems with the navigation bar 

### ISSUE THREAD

**Issue by MayckonJhonatas** [zeh/unity-tidbits#4]
I did put to show the status bar, but i don't wanna the navigation bar but the navigation bar is not getting hidden.

**Comment by zeh** [comment]
Hey @MayckonJhonatas,

That's because of (somewhat) recent changes to [how Android's navigation bar works](https://developer.android.com/training/system-ui/navigation.html#40)...

> Once the flags have been cleared, your app needs to reset them if you want to hide the bars again. See Responding to UI Visibility Changes for a discussion of how to listen for UI visibility changes so that your app can respond accordingly.

I'm thinking of a new API to take this into consideration.

**Comment by zeh** [comment]
Yay! I just [committed a fix](https://github.com/zeh/unity-tidbits/commit/2776f631963e8263dd1a3bc9e47a90f716c0de35). Setting the navigation to hidden works again; it stays hidden.

I can't be 100% sure _why_ this started happening now, but: it seems a recent version of Unity started listening to UI/View flag changes performed by `setSystemUiVisibility` and applying changes of its own. So what the new code does is _remove_ any listener previously set, so there won't be anything being undone.

This likely conflicts with Unity's use of `Screen.fullScreen`, but that's to be expected, since setting that command sets flags of its own. Instead, when using ApplicationChrome, it's best to ignore `Screen.fullScreen` altogether, and only use `ApplicationChrome`.

Other weird side effects (e.g. sometimes changing navigation settings also change status bar settings...) still exist, but it's an unavoidable issue to due to how Android's view flags work. There's nothing that can be done from our side. :/

**Comment by kbobnis** [comment]
Hi, I am still getting this bug.

If I show the status bar then navigation bar will always show, even if set to hidden.

Phone: Pixel 2, android 10, unity 2019.3.0f6

```
ApplicationChrome.statusBarState = ApplicationChrome.States.TranslucentOverContent;
ApplicationChrome.navigationBarState = ApplicationChrome.States.Hidden;
```

will result in both bars visible.

**Comment by zeh** [comment]
@kbobnis I believe Unity changed something in the way the UI bar flags are handled internally, making it very difficult to deal with them as is. Always showing navigation bars in some cases is indeed a side effect I noticed sometimes.

Unfortunately it's not just a matter of "fixing" bugs as is. These changes seem to require a different approach (removing Unity's own events for UI changes, overwriting flags on different situations, waiting a frame here and there, etc).

I've started [a separate project](https://github.com/zeh/unity-screen-bars/tree/dev) _just_ to be able to handle this on a more focused fashion. Unfortunately the project is not ready for release yet...

On your case, what I recommend is maybe changing the order those changes get set (e.g. `navigationBarState` before `statusBarState`); maybe waiting a frame between each call; maybe changing the Unity player setting for Android on whether to use fullScreen or not; maybe not using `Screen.fullScreen` yourself, if you are.

I know it doesn't fully solve your problem, so sorry about that. But there's more work to be done here for this to be fully fixed.
